---
mark_packages:
  - exfatprogs
  - gdisk

purge_packages:
  - udisks2

purge_packages_armhf:
  - gcc-10-base
  - gcc-7-base
  - gcc-8-base
  - gcc-9-base
  - install-info
  - libfribidi0
  - libsigc++-1.2-5c2
  - lsb-base
  - paxctld
