---
- include_vars: apt-sources.yml

- name: get architecture
  shell: dpkg --print-architecture
  register: dpkg_architecture

- name: set architecture as a fact
  set_fact:
    mechatrax_architecture: "{{ dpkg_architecture.stdout }}"

- name: get release
  shell: lsb_release -cs
  register: lsb_release

- name: set release as a fact
  set_fact:
    mechatrax_release: "{{ lsb_release.stdout }}"

- name: include vars
  include_vars: '{{ mechatrax_release }}.yml'

- name: determine repo format
  set_fact:
    mechatrax_config: "{{ formats[repo_map[mechatrax_release] | default(defaults.format)] }}"

- name: download mechatrax keyring
  get_url: url=https://mechatrax.github.io/raspbian/pool/main/m/mechatrax-archive-keyring/{{ mechatrax_archive_keyring_deb }}
           dest=/tmp/{{ mechatrax_archive_keyring_deb }}
           checksum=sha256:{{ mechatrax_archive_keyring_sha256sum }}
  when: mechatrax_config.keyring

- name: install mechatrax keyring
  apt: deb=/tmp/{{ mechatrax_archive_keyring_deb }}
  when: mechatrax_config.keyring

- name: add mechatrax apt repository
  template: src={{ mechatrax_config.template }}
            dest=/etc/apt/sources.list.d/{{ mechatrax_config.filename }}
            owner=root
            group=root
            mode=0644

- name: update caches
  apt: update_cache=yes

- name: detect chroot
  command: systemd-detect-virt --chroot
  register: chroot_result
  ignore_errors: true

- name: set chroot fact
  set_fact:
    is_chroot: "{{ chroot_result.rc == 0 }}"

- name: run chroot setup if in chroot
  include_role:
    name: chroot
    tasks_from: setup
  when: is_chroot
