---
install_packages:
  - 3gpi-utils
  - 3gpi-network-manager
  - 4gpi-net-mods
  - jo
  - jq
  - gpsd
  - gpsd-clients
  - modemmanager
  - network-manager
  - rng-tools
  - soracom-cli
  - ufw

purge_packages:
  - gcc-4.9-base
  - gcc-5-base
  - gcc-6-base
  - gcc-7-base
  - freetype2-doc
  - libraspberrypi-doc
  - libboost-iostreams1.58.0
  - libudev0
  - libsigc++-1.2-5c2

