---
- name: remove unused packages
  apt: autoremove=yes

- name: list removed packages
  shell: dpkg -l | awk '/^rc/{ sub(":armhf", "", $2); sub(":arm64", "", $2); print $2 }'
  register: removed_packages

- name: purge configurations
  apt: name={{ removed_packages.stdout_lines }} purge=yes state=absent

- name: get old kernel packages
  shell: dpkg -l linux-image-* linux-headers-* | grep -v $(dpkg -l linux-image-rpi-* | awk '/^ii/{print$3}' | sort -n | uniq) | awk '/^ii/{print$2}'
  register: old_kernel_packages

- name: detect chroot
  command: systemd-detect-virt --chroot
  register: result
  ignore_errors: true

- name: purge old kernel packages
  apt: name={{ old_kernel_packages.stdout_lines }} state=absent purge=yes
  when: result.rc == 0

